plugins {
    id 'net.fabricmc.fabric-loom' version '1.18-SNAPSHOT'
    id 'maven-publish'
    id 'java'
    id 'com.gradleup.shadow' version "9.4.1"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name + "-MC${sc.current.version}"
}

repositories {
    mavenCentral()
    maven { url = uri("https://repo.lunarclient.dev") }
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    minecraft "com.mojang:minecraft:${sc.current.version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    def fabricApiVersion = '0.155.3'

    if (sc.current.parsed.matches('>=26.2')) {
        fabricApiVersion = '0.161.0'
    }

    implementation "net.fabricmc.fabric-api:fabric-api:${fabricApiVersion}+${sc.current.version}"

    def shadowDeps = [
            'io.github.jseproject:jse-spi-speex:1.1.0',
            'javazoom:jlayer:1.0.1',
            'com.google.protobuf:protobuf-java:3.25.0',
            'com.lunarclient:apollo-protos:+',
            'org.java-websocket:Java-WebSocket:1.6.0',
            'org.endlesssource.mediainterface:all:+'
    ]

    shadowDeps.each {
        implementation it
        shadow it
    }
}

// https://github.com/EndlessSource/mediainterface
tasks.shadowJar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    mergeServiceFiles {
        include("META-INF/services/org.endlesssource.mediainterface.spi.PlatformMediaProvider")
    }
    destinationDirectory = rootProject.layout.projectDirectory.dir("out")
}

tasks.clean {
    delete rootProject.layout.projectDirectory.dir("out")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", sc.current.version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": sc.current.version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 25

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }

    dependsOn shadowJar
}

shadowJar {
    configurations = [project.configurations.shadow]
    exclude("META-INF")
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    repositories {
    }
}