# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.2
# Mod Properties
mod_version=1.1
maven_group=cc.vops
archives_base_name=CheatBreaker
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.147.0+26.1.2